# This is a basic workflow to help you get started with Actions

name: Sync JSON Data

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "*/5 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync-json-data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Sync data
        run: |
          curl -s "https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json" > data.json
      
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if ! git diff --exit-code; then
            git add *
            git commit -m "Synced JSON data"
            git push
          fi